version: '3.8'

services:
  # Banco de dados MongoDB para Auth.API
  mongodb:
    image: mongo:latest
    container_name: odontoprev-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    volumes:
      - mongodb_data:/data/db
    networks:
      - odontoprev-network
    restart: unless-stopped

  # Message broker RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: odontoprev-rabbitmq
    ports:
      - "5672:5672"   # Porta AMQP
      - "15672:15672" # Porta de gerenciamento
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - odontoprev-network
    restart: unless-stopped

  # Auth.API - Servico de autenticacao
  auth-api:
    build:
      context: ../src/Auth.API
      dockerfile: Dockerfile
    container_name: odontoprev-auth-api
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDBSettings__ConnectionString=mongodb://admin:adminpassword@mongodb:27017
      - MongoDBSettings__DatabaseName=OdontoprevAuth
      - RabbitMQSettings__HostName=rabbitmq
      - RabbitMQSettings__UserName=guest
      - RabbitMQSettings__Password=guest
      - RabbitMQSettings__Port=5672
      - RabbitMQSettings__AuthExchange=auth_exchange
      - RabbitMQSettings__UserCreatedQueue=user_created_queue
      - RabbitMQSettings__UserLoggedInQueue=user_loggedin_queue
      - JwtSettings__Key=QaEaH3mDHuQRXBTk2wmRsGG6VrZt4Qe2
      - JwtSettings__Issuer=OdontoprevAuthAPI
      - JwtSettings__Audience=OdontoprevApps
      - JwtSettings__ExpireMinutes=60
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - odontoprev-network
    restart: unless-stopped

  # Challenge_Odontoprev_API - API principal
  odontoprev-api:
    build:
      context: ../src/Challenge_Odontoprev_API
      dockerfile: Dockerfile
    container_name: odontoprev-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__OracleConnection=Data Source=//oracle:1521/XEPDB1;User Id=system;Password=oracle;
      - RabbitMQSettings__HostName=rabbitmq
      - RabbitMQSettings__UserName=guest
      - RabbitMQSettings__Password=guest
      - RabbitMQSettings__Port=5672
      - RabbitMQSettings__AuthExchange=auth_exchange
      - RabbitMQSettings__UserCreatedQueue=user_created_queue
      - RabbitMQSettings__UserLoggedInQueue=user_loggedin_queue
      - JwtSettings__Key=QaEaH3mDHuQRXBTk2wmRsGG6VrZt4Qe2
      - JwtSettings__Issuer=OdontoprevAuthAPI
      - JwtSettings__Audience=OdontoprevApps
      - JwtSettings__ExpireMinutes=60
    depends_on:
      - rabbitmq
      - auth-api
    networks:
      - odontoprev-network
    restart: unless-stopped

# Define as redes - esta secao deve estar no mesmo nivel que 'services', nao dentro dela
networks:
  odontoprev-network:
    driver: bridge

# Define os volumes - esta secao deve estar no mesmo nivel que 'services', nao dentro dela
volumes:
  mongodb_data:
  rabbitmq_data: